apiVersion: v1
kind: Service

metadata:
  name: agrocorelogin-service

spec:
  type: NodePort

  selector:
    app: agrocorelogin

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
