# =========================
# DEPLOYMENT
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrocorelogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrocorelogin

  template:
    metadata:
      labels:
        app: agrocorelogin

    spec:
      containers:
        - name: agrocorelogin
          image: euturial/agrocorelogin:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

---
# =========================
# SERVICE (ClusterIP)
# =========================
apiVersion: v1
kind: Service
metadata:
  name: agrocorelogin
spec:
  type: ClusterIP

  selector:
    app: agrocorelogin

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
# =========================
# INGRESS
# =========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agrocorelogin-ingress

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
    - host: apiagrocorelogin
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agrocorelogin
                port:
                  number: 80
